import React, { useState } from "react";
import Head from 'next/head';
import HomePageSlider from './components/HomePageSlider';

export default function Home(props) {

  const [sliders, setSliders] = useState(props.sliders);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePageSlider sliders={sliders} />
      </main>
      
    </>
  )
}

export async function getServerSideProps(context) {
  const data = await fetch(`http://localhost:5000/api/homepage/all`);
  const sliders = await data.json();
  return {
    props: { sliders }, // will be passed to the page component as props
  };
}
